### ISSUE TITLE
Errors in pagenumbers in dkw2ucs.txt

### ISSUE THREAD

**Issue by rtega** [cjkvi/cjkvi-dict#2]
I created page numbers for the Morohashi and after careful checking noticed a bunch of differences between my data and the data in dkw2ucs.txt-file. The ones relating to the *.1 numbers (i.e.: like number 01368.1 or 13681' in Morohashi) are probably due to differences in editions. I have the 1984 edition (the third revision), yours is probably based and the 1st or 2nd edition. Everything else is probably an error in dkw2ucs.txt. I included a dump with the following format:
<Morohashi number> <page number according to dkw2ucs.txt> - <volume>.<page number according to my edition>
[checkmorohashi2a.txt](https://github.com/cjkvi/cjkvi-dict/files/1314879/checkmorohashi2a.txt)

If you want the data in any other format, please let me know. I also included the mysqldump of the relevant table in my dbase.
[moro_order.sql.gz](https://github.com/cjkvi/cjkvi-dict/files/1314886/moro_order.sql.gz)

Kind regards,

Reinaert

**Comment by kawabata** [comment]
Thanks for your info.

My data is also based on Third edition, but in the old days, it had been basedn on the
2nd edition for a while.

By taking a glance at your data, it seems your proposal seems to be all correct.

I will plan to fix it as soon as the time is available, but sorry, I will be busy for several
weeks and it may take a time to fix all of them.

**Comment by rtega** [comment]
Thanks for looking at the data!

I wonder whether it's useful to have two sets of data for the differing editions. Maybe having a separate database is more concise than having all the data written out in the txt-file?

**Comment by kawabata** [comment]
Well, I think that's a matter of the users.  It would be easy to split or merge by simple scripts.

**Comment by rtega** [comment]
Probably it's good to maintain a txt-file describing the pagenumbers of the differing editions here?

**Comment by kawabata** [comment]
updated.
I really appreciate.

I found that these are purely mistakes, not based on the older versions.
As I couldn't maintain multiple versions, will stick on 3rd edition.

**Comment by rtega** [comment]
Sure, I'll have a look with Jim Breen (wwwjdict and kanjidic) who has the first edition to see whether he'll want to maintain the version for the 1st edition.

**Comment by rtega** [comment]
BTW, my full name is Reinaert Albrecht ;)

**Comment by kawabata** [comment]
;->  Thanks Albrecht-san!
